---
- name: Update Mikrometer System
  hosts: all
  become: true

  vars:
    update_summary: []

  tasks:
    - name: Change ownership to ansible user
      ansible.builtin.command:
        cmd: "sudo chown -R {{ ansible_user }}:{{ ansible_user }} {{ mikrometer_path }}"

    - name: Ensure latest code from GitHub
      ansible.builtin.git:
        repo: "https://github.com/AfriPos/mikrometer.git"
        dest: "{{ mikrometer_path }}"
        version: main
        force: yes
        update: yes
      become: false
      register: git_pull_result

    - name: Add Git pull to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Git repository updated'] }}"
      when: git_pull_result is defined

    - name: Composer update
      ansible.builtin.command:
        cmd: composer update
        chdir: "{{ mikrometer_path }}"
      register: composer_result
      become: false

    - name: Add Composer update to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Composer dependencies updated'] }}"
      when: composer_result is defined

    - name: Run database migrations (force yes in production)
      ansible.builtin.shell: |
        yes | php artisan migrate --force
      args:
        chdir: "{{ mikrometer_path }}"
      register: migration_result
      become: false

    - name: Add database migrations to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Database migrations executed'] }}"
      when: migration_result is defined

    - name: Run database seeder (force in production)
      ansible.builtin.shell: |
        yes | php artisan db:seed --force
      args:
        chdir: "{{ mikrometer_path }}"
      register: seeder_result
      become: false

    - name: Add database seeding to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Database seeding executed'] }}"
      when: seeder_result is defined

    - name: Make vite executable
      ansible.builtin.command:
        cmd: chmod +x node_modules/.bin/vite
        chdir: "{{ mikrometer_path }}"
      register: vite_result
      become: true

    - name: Add Vite executable to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Vite permissions set'] }}"
      when: vite_result is defined

    - name: Make esbuild executable
      ansible.builtin.command:
        cmd: chmod +x node_modules/@esbuild/linux-x64/bin/esbuild
        chdir: "{{ mikrometer_path }}"
      register: esbuild_result
      become: true

    - name: Add Esbuild executable to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Esbuild permissions set'] }}"
      when: esbuild_result is defined

    - name: NPM update & install
      ansible.builtin.command:
        cmd: sudo npm install
        chdir: "{{ mikrometer_path }}"
      register: npm_install_result
      become: false

    - name: Add NPM install to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ NPM dependencies installed'] }}"
      when: npm_install_result is defined

    - name: NPM build
      ansible.builtin.command:
        cmd: sudo npm run build
        chdir: "{{ mikrometer_path }}"
      register: npm_build_result
      become: false

    - name: Add NPM build to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Frontend assets built'] }}"
      when: npm_build_result is defined

    - name: Laravel artisan cache commands
      ansible.builtin.shell: |
        sudo php artisan optimize:clear
        sudo php artisan config:cache
        sudo php artisan route:cache
        sudo php artisan view:cache
        sudo php artisan event:cache
        sudo php artisan queue:restart
      args:
        chdir: "{{ mikrometer_path }}"
      register: cache_result

    - name: Add cache commands to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Laravel caches refreshed'] }}"
      when: cache_result is defined

    - name: Change ownership back to mikrometer_user
      ansible.builtin.command:
        cmd: "sudo chown -R {{ mikrometer_user }}:{{ mikrometer_user }} {{ mikrometer_path }}"
      register: ownership_result

    - name: Add ownership change to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Ownership restored to mikrometer_user'] }}"
      when: ownership_result is defined

    - name: Change permissions back to mikrometer_group
      ansible.builtin.command:
        cmd: "sudo chmod -R g+w {{ mikrometer_path }}"
      register: permissions_result

    - name: Add permissions change to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Group write permissions set'] }}"
      when: permissions_result is defined

    - name: Restart supervisor service
      ansible.builtin.command:
        cmd: sudo systemctl restart supervisor
      register: supervisor_result
      become: true
    
    - name: Add supervisor restart to summary
      ansible.builtin.set_fact:
        update_summary: "{{ update_summary + ['✓ Supervisor service restarted'] }}"
      when: supervisor_result is defined

    - name: Show update summary
      ansible.builtin.debug:
        msg: |
          🚀 DEPLOYMENT SUMMARY:
          {% for item in update_summary %}
          {{ item }}
          {% endfor %}
          Total tasks completed: {{ update_summary | length }}

    - name: Show final completion message
      ansible.builtin.debug:
        msg: "✅ Deployment process completed successfully!"