- name: Test sudo and APT access
  hosts: all
  become: yes
  tasks:
    - name: Test sudo access
      command: whoami
      register: whoami_result
    
    - name: Show whoami result
      debug:
        var: whoami_result.stdout

    - name: Test if we can access apt
      command: sudo apt update
      register: apt_test
      ignore_errors: yes
    
    - name: Show apt test result
      debug:
        var: apt_test