---
- name: Reboot all servers
  hosts: all
  become: yes

  tasks:
    - name: Reboot server using sudo shutdown
      ansible.builtin.command:
        cmd: "sudo shutdown -r +1 'Ansible triggered reboot'"
      async: 1
      poll: 0
      register: reboot_cmd

    - name: Wait for server to come back online
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        sleep: 10
        delay: 30
        timeout: 600

    - name: Verify system is back online
      ansible.builtin.ping:
