---
- name: Reboot all servers
  hosts: all
  become: yes
  gather_facts: no  # Disable initial fact gathering

  tasks:
    - name: Reboot server using sudo shutdown
      ansible.builtin.command:
        cmd: "sudo shutdown -r +1 'Ansible triggered reboot'"
      async: 1
      poll: 0

    - name: Wait for server to come back online
      ansible.builtin.wait_for_connection:
        delay: 120  # Wait 2 minutes before starting checks
        timeout: 300  # 5 minute timeout total

    - name: Simple connectivity test (skip fact gathering)
      ansible.builtin.ping:

    - name: Optional - Gather facts only after confirming connectivity
      ansible.builtin.setup:
      when: false  # Disable by default, set to true if you need facts
