---
- name: Test sudo functionality
  hosts: all
  become: yes

  tasks:
    - name: Test basic sudo command
      ansible.builtin.command:
        cmd: "sudo whoami"
      register: sudo_test

    - name: Show sudo test result
      ansible.builtin.debug:
        var: sudo_test.stdout

    - name: Test sudo with reboot command
      ansible.builtin.command:
        cmd: "sudo shutdown -r +1"
      register: reboot_test
      async: 1
      poll: 0
      ignore_errors: yes

    - name: Show reboot test result
      ansible.builtin.debug:
        var: reboot_test