---
- name: Reboot all servers
  hosts: all
  become: yes

  tasks:
    - name: Reboot server using sudo shutdown
      ansible.builtin.command:
        cmd: "sudo shutdown -r +1 'Ansible triggered reboot'"
      async: 1
      poll: 0

    - name: Wait for server to come back online
      ansible.builtin.wait_for_connection:
        connect_timeout: 30
        sleep: 10
        delay: 90  # Start checking after 90 seconds to account for reboot time
        timeout: 600  # Total 10 minute timeout

    - name: Verify system is back online
      ansible.builtin.ping:
