---
- name: Update firewalld rules
  hosts: all
  become: true
  vars:
    allowed_ips:
      - "134.255.183.25"
      - "89.117.50.10"
      - "109.199.112.131"
      - "109.199.104.81"
      - "158.220.122.127"
      - "144.91.92.23"
      - "37.60.247.176"

    services:
      - smtp
      - smtps
      - "smtp-submission"
      - imap
      - imaps
      - pop3
      - pop3s
      - ftp

    virtualmin_ports:
      - 10000
      - 20000
      - 2222

    ftp_ports:
      - 21
      - 2222

  tasks:
    - name: Remove Virtualmin/Webmin ports from public zone
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --zone=public --remove-port={{ item }}/tcp --permanent"
      loop: "{{ virtualmin_ports }}"
      ignore_errors: yes

    - name: Remove mail services from public zone
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --zone=public --remove-service={{ item }} --permanent"
      loop: "{{ services }}"
      ignore_errors: yes

    - name: Create an ipset for allowed FTP/SFTP IPs
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --permanent --new-ipset=ftp_allowed --type=hash:ip"
      register: ipset_create
      failed_when: ipset_create.rc != 0 and 'already exists' not in (ipset_create.stdout + ipset_create.stderr | default(''))
      ignore_errors: yes

    - name: Add allowed IPs to ipset
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --permanent --ipset=ftp_allowed --add-entry={{ item }}"
      loop: "{{ allowed_ips }}"

    - name: Allow FTP + SFTP only from the ipset
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source ipset=ftp_allowed port port={{ item }} protocol=tcp accept'"
      loop: "{{ ftp_ports }}"

    - name: Allow Virtualmin/Webmin only from server IP
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source address={{ ansible_host }} port port={{ item }} protocol=tcp accept'"
      loop: "{{ virtualmin_ports }}"

    - name: Reload firewalld
      ansible.builtin.command:
        cmd: "sudo firewall-cmd --reload"
