---
- name: Update firewalld rules
  hosts: all
  become: true
  vars:
    allowed_ips:
      - "134.255.183.25"
      - "89.117.50.10"
      - "109.199.112.131"
      - "109.199.104.81"
      - "158.220.122.127"
      - "144.91.92.23"
      - "37.60.247.176"

    services:
      - smtp
      - smtps
      - "smtp-submission"
      - imap
      - imaps
      - pop3
      - pop3s
      - ftp

    virtualmin_ports:
      - 10000
      - 20000
      - 2222

    ftp_ports:
      - 21
      - 2222

  tasks:
    - name: Remove Virtualmin/Webmin ports from public zone
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}/tcp"
        state: absent
        permanent: true
      loop: "{{ virtualmin_ports }}"

    - name: Remove mail services from public zone
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        state: absent
        permanent: true
      loop: "{{ services }}"

    - name: Ensure ipset exists for FTP/SFTP allowed IPs
      ansible.posix.firewalld:
        ipset: ftp_allowed
        type: hash:ip
        state: present
        permanent: true

    - name: Add allowed IPs to ipset
      ansible.posix.firewalld:
        ipset: ftp_allowed
        entry: "{{ item }}"
        state: present
        permanent: true
      loop: "{{ allowed_ips }}"

    - name: Allow FTP + SFTP only from allowed IPs
      ansible.posix.firewalld:
        zone: public
        rich_rule: 'rule family="ipv4" source ipset="ftp_allowed" port port="{{ item }}" protocol="tcp" accept'
        state: enabled
        permanent: true
      loop: "{{ ftp_ports }}"

    - name: Allow Virtualmin/Webmin only from server IP
      ansible.posix.firewalld:
        zone: public
        rich_rule: 'rule family="ipv4" source address="{{ ansible_host }}" port port="{{ item }}" protocol="tcp" accept'
        state: enabled
        permanent: true
      loop: "{{ virtualmin_ports }}"

    - name: Reload firewalld
      ansible.posix.firewalld:
        state: reloaded
