---
- name: Update firewalld rules
  hosts: all
  become: true
  vars:
    # List of IPs allowed to access FTP/SFTP
    allowed_ips:
      - "134.255.183.25"
      - "89.117.50.10"
      - "109.199.112.131"
      - "109.199.104.81"
      - "158.220.122.127"
      - "144.91.92.23"
      - "37.60.247.176"

    # Mail services to remove from public
    mail_services:
      - smtp
      - smtps
      - "smtp-submission"
      - imap
      - imaps
      - pop3
      - pop3s

    # Ports used by Virtualmin/Webmin
    virtualmin_ports:
      - 10000
      - 20000

    # FTP/SFTP ports
    ftp_ports:
      - 21
      - 2222

  tasks:
    - name: Remove Virtualmin/Webmin ports from public zone
      ansible.builtin.command:
        cmd: "firewall-cmd --zone=public --remove-port={{ item }}/tcp --permanent"
      loop: "{{ virtualmin_ports }}"
      ignore_errors: yes
      notify: Reload firewalld

    - name: Remove mail services from public zone
      ansible.builtin.firewalld:
        zone: public
        service: "{{ item }}"
        state: absent
        permanent: true
      loop: "{{ mail_services }}"
      notify: Reload firewalld

    - name: Create an ipset for allowed FTP/SFTP IPs
      ansible.builtin.command:
        cmd: "firewall-cmd --permanent --new-ipset=ftp_allowed --type=hash:ip"
      args:
        warn: false
      register: ipset_create
      failed_when: "'already exists' not in ipset_create.stderr and ipset_create.rc != 0"

    - name: Add allowed IPs to ipset
      ansible.builtin.command:
        cmd: "firewall-cmd --permanent --ipset=ftp_allowed --add-entry={{ item }}"
      loop: "{{ allowed_ips }}"

    - name: Allow FTP + SFTP only from the ipset
      ansible.builtin.firewalld:
        zone: public
        rich_rule: 'rule family="ipv4" source ipset="ftp_allowed" port port="{{ item }}" protocol="tcp" accept'
        state: enabled
        permanent: true
      loop: "{{ ftp_ports }}"
      notify: Reload firewalld

    - name: Allow Virtualmin/Webmin only from server IP
      ansible.builtin.firewalld:
        zone: public
        rich_rule: 'rule family="ipv4" source address="{{ ansible_host }}" port port="{{ item }}" protocol="tcp" accept'
        state: enabled
        permanent: true
      loop: "{{ virtualmin_ports }}"
      notify: Reload firewalld

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
