---
- name: Copy MOTD from one server to all others
  hosts: all
  become: true
  vars:
    motd_source_host: cp2      # The host you want to copy the MOTD *from*
    motd_temp_path: /tmp/motd-temp

  tasks:
    - name: Fetch MOTD from source host
      fetch:
        src: /etc/motd
        dest: "{{ motd_temp_path }}"
        flat: yes
      delegate_to: "{{ motd_source_host }}"
      run_once: true

    - name: Copy MOTD to all other servers
      copy:
        src: "{{ motd_temp_path }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
      become: true
