---
- name: Copy MOTD file from control node to all remote servers
  hosts: all
  become: true
  vars:
    source_motd_path: /etc/motd
    dest_motd_path: /etc/motd

  tasks:
    - name: Copy MOTD from control node to remote servers
      copy:
        src: "{{ source_motd_path }}"
        dest: "{{ dest_motd_path }}"
        owner: root
        group: root
        mode: '0600'
      ignore_errors: true
