---
- name: Copy MOTD from a main server to all other servers
  hosts: all
  become: true
  vars:
    motd_source_host: cp2
    motd_temp_path: /tmp/motd-temp

  tasks:
    - name: Fetch MOTD from source host (cp2)
      fetch:
        src: /etc/motd
        dest: "{{ motd_temp_path }}"
        flat: yes
      delegate_to: "{{ motd_source_host }}"
      run_once: true
      become: true

    - name: Copy MOTD to all other servers
      copy:
        src: "{{ motd_temp_path }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Clean up temporary MOTD file from Semaphore worker
      delegate_to: localhost
      file:
        path: "{{ motd_temp_path }}"
        state: absent
      run_once: true
