---
- name: Test become on all servers
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: show whoami (should be root)
      command: whoami
      register: who
    - name: debug whoami
      debug:
        msg: "{{ inventory_hostname }} -> {{ who.stdout }}"

    - name: try writing /etc/testfile (verifies write permission)
      file:
        path: /etc/ansible_testfile
        state: touch
      become: true
